"use client";

import { useEffect, useRef, useState } from "react";
import { CircleStop, Mic, Play, Video } from "lucide-react";

const prompts = [
  "Describe a high-pressure work decision and how you handled accountability.",
  "Tell us about a conflict with a colleague and what changed afterward.",
  "How do you manage deadlines when priorities compete?"
];

export default function InterviewRoom({ params }: { params: { token: string } }) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const recorderRef = useRef<MediaRecorder | null>(null);
  const [recording, setRecording] = useState(false);
  const [chunks, setChunks] = useState<Blob[]>([]);
  const [question, setQuestion] = useState(0);
  const [transcript, setTranscript] = useState("");

  useEffect(() => {
    navigator.mediaDevices?.getUserMedia({ video: true, audio: true }).then((stream) => {
      if (videoRef.current) videoRef.current.srcObject = stream;
      recorderRef.current = new MediaRecorder(stream);
      recorderRef.current.ondataavailable = (event) => setChunks((current) => [...current, event.data]);
    }).catch(() => null);
  }, []);

  const start = () => {
    setChunks([]);
    recorderRef.current?.start();
    setRecording(true);
  };

  const stop = () => {
    recorderRef.current?.stop();
    setRecording(false);
    setTranscript("Transcript preview will be generated by the backend Whisper pipeline after upload. Candidate discussed accountability, delivery pressure, and team communication.");
  };

  return (
    <main className="min-h-screen bg-[#eef3ef] p-4 md:p-8">
      <div className="mx-auto grid max-w-7xl gap-5 xl:grid-cols-[1fr_380px]">
        <section className="surface rounded-lg p-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-bold uppercase tracking-widest text-forest/60">Interview session</p>
              <h1 className="text-2xl font-black text-forest">{params.token}</h1>
            </div>
            <span className="rounded-full bg-white px-3 py-1 text-sm font-bold text-forest">{recording ? "Recording" : "Ready"}</span>
          </div>
          <video ref={videoRef} autoPlay muted playsInline className="mt-4 aspect-video w-full rounded-lg bg-slate-900 object-cover" />
          <div className="mt-4 rounded-lg bg-white p-4">
            <p className="text-xs font-black uppercase tracking-widest text-sage">Question {question + 1} of {prompts.length}</p>
            <h2 className="mt-2 text-xl font-black">{prompts[question]}</h2>
            <div className="mt-4 flex flex-wrap gap-2">
              <button className="btn btn-primary" onClick={start}><Play size={17} /> Start</button>
              <button className="btn btn-secondary" onClick={stop}><CircleStop size={17} /> Stop</button>
              <button className="btn btn-secondary" onClick={() => setQuestion((question + 1) % prompts.length)}>Next question</button>
              <label className="btn btn-secondary cursor-pointer">Upload fallback<input type="file" accept="video/*,audio/*" className="hidden" /></label>
            </div>
          </div>
        </section>
        <aside className="grid gap-4">
          <article className="surface rounded-lg p-5">
            <h2 className="text-xl font-black">Live AI Analysis</h2>
            {["Confidence 78", "Stress resilience 71", "Leadership presence 82", "Team risk 24"].map((metric) => <div key={metric} className="mt-3 rounded-lg bg-white p-3 text-sm font-bold text-forest">{metric}</div>)}
          </article>
          <article className="surface rounded-lg p-5">
            <h2 className="text-xl font-black">Transcript</h2>
            <p className="mt-3 text-sm leading-6 text-slate-600">{transcript || "Transcript preview appears after recording or upload."}</p>
          </article>
          <article className="surface rounded-lg p-5">
            <h2 className="text-xl font-black">Media captured</h2>
            <p className="mt-2 text-sm text-slate-600">{chunks.length} encrypted browser chunks ready for upload.</p>
            <div className="mt-4 flex gap-2 text-forest"><Video /><Mic /></div>
          </article>
        </aside>
      </div>
    </main>
  );
}

